/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.uniminuto.gui;

import co.edu.uniminuto.dao.ProductoDao;
import co.edu.uniminuto.entity.Producto;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Manuel Sanchez Narvaez
 *         NRC 50 - 55257
 *         ID 001000940
 *         Arli Jaidybe Gaita Jara
 *         NRC 50 - 55257
 *         ID 981058
 */
public class ActualizarProducto extends javax.swing.JInternalFrame {

    DefaultTableModel modeloTabla;

    public ActualizarProducto() {
        modeloTabla = new DefaultTableModel(null, getColumns());
        initComponents();
        dataProductos();
    }

    //metodo para colocar nombre a las columnas
    private String[] getColumns() {
        String columns[] = new String[]{"id", "Nombre", "Cantidad", "Precio por unidad", "Estatus"};
        return columns;
    }

    //Obtener datos para la tabla
    private void dataProductos() {
        ProductoDao dao = new ProductoDao();
        ResultSet resultSet;
        try {
            resultSet = dao.queryProducto();
            Object datos[] = new Object[5];
            while (resultSet.next() == true) {
                for (int i = 0; i < 5; i++) {
                    datos[i] = resultSet.getObject(i + 1);
                }
                modeloTabla.addRow(datos);
            }
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        lvlProductoId = new javax.swing.JLabel();
        txtProductoNombre = new javax.swing.JTextField();
        lvlProductoNombre = new javax.swing.JLabel();
        lvlProductoCantidad = new javax.swing.JLabel();
        txtProductoCantidad = new javax.swing.JTextField();
        lvlProductoPrecio = new javax.swing.JLabel();
        txtPrecioUnidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lvlMensage2 = new javax.swing.JLabel();
        lvlMensage1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spnProductoId = new javax.swing.JSpinner();
        spnProductoEstado = new javax.swing.JSpinner();

        TablaProductos.setModel(modeloTabla);
        jScrollPane1.setViewportView(TablaProductos);

        lvlProductoId.setText("id del Producto:");

        lvlProductoNombre.setText("Nombre del Producto:");

        lvlProductoCantidad.setText("Cantidad del Producto:");

        lvlProductoPrecio.setText("Precio por Unidad:");

        jLabel5.setText("Estado del producto:");

        lvlMensage2.setText("Escribe \"0\" para eliminar y \"1\" para guardar en la lista");

        lvlMensage1.setText("Rellena los datos para actualizar el producto");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lvlProductoId)
                                            .addComponent(lvlProductoNombre)
                                            .addComponent(lvlProductoPrecio))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCancelar)
                                            .addComponent(jLabel5))
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lvlProductoCantidad)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProductoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txtProductoCantidad)
                                    .addComponent(txtPrecioUnidad)
                                    .addComponent(spnProductoId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnProductoEstado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lvlMensage1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lvlMensage2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lvlMensage1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lvlProductoId)
                        .addComponent(spnProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtProductoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lvlProductoCantidad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lvlProductoPrecio)))
                            .addComponent(lvlProductoNombre))))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlMensage2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnProductoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(20, 61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (spnProductoId.getValue() != null && txtProductoNombre.getText() != "" && txtProductoCantidad.getText() != "" && txtPrecioUnidad.getText() != "" && spnProductoEstado.getValue() != null) {

            int productoId = (int) spnProductoId.getValue();
            int productoEstado = (int) spnProductoEstado.getValue();

            ProductoDao productoDao = new ProductoDao();
            Producto producto = new Producto(productoId, txtProductoNombre.getText(), txtProductoCantidad.getText(), txtPrecioUnidad.getText(), productoEstado);
            productoDao.ActualizarProducto(producto);

            dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Error, debes completar toda la información del producto pora poder actualizar.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvlMensage1;
    private javax.swing.JLabel lvlMensage2;
    private javax.swing.JLabel lvlProductoCantidad;
    private javax.swing.JLabel lvlProductoId;
    private javax.swing.JLabel lvlProductoNombre;
    private javax.swing.JLabel lvlProductoPrecio;
    private javax.swing.JSpinner spnProductoEstado;
    private javax.swing.JSpinner spnProductoId;
    private javax.swing.JTextField txtPrecioUnidad;
    private javax.swing.JTextField txtProductoCantidad;
    private javax.swing.JTextField txtProductoNombre;
    // End of variables declaration//GEN-END:variables
}
